---------- CONSULTAS ----------

----- CONSULTA 1 -----

---INFORME 1---
SELECT 
     FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD"
FROM PROPIEDAD
WHERE FECHA_ENTREGA_PROPIEDAD BETWEEN '01/01/25' AND '31/12/25'
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC

---INFORME 2---

SELECT 
    FECINI_ARRIENDO AS "FECHA INICIO ARRIENDO"
FROM PROPIEDAD_ARRENDADA
WHERE FECINI_ARRIENDO BETWEEN '01/01/25' AND '31/12/25'
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC

----- CONSULTA 2 -----

SELECT
    NUMRUT_CLI||'-'||DVRUT_CLI AS "RUT CLIENTE",
    NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI AS "NOMBRE CLIENTE",
    RENTA_CLI AS "RENTA",
    FONOFIJO_CLI AS "FONO FIJO",
    CELULAR_CLI AS "CELULAR"
FROM
    CLIENTE
WHERE RENTA_CLI >= 800000 AND ID_ESTCIVIL IN(1,3,4)
ORDER BY APPATERNO_CLI,NOMBRE_CLI ASC

----- CONSULTA 3 -----

---INFORME 1---

SELECT 
      NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
      SUELDO_EMP AS "SUELDO ACTUAL",
      SUELDO_EMP*0.085 AS "AUMENTO",
      SUELDO_EMP*1.085 AS"SUELDO REAJUSTADO"
FROM 
    EMPLEADO
ORDER BY 2 DESC

---INFORME 2---

SELECT 
      NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
      SUELDO_EMP AS "SUELDO ACTUAL",
      SUELDO_EMP*0.20 AS "AUMENTO",
      SUELDO_EMP*1.20 AS "SUELDO REAJUSTADO"
FROM 
    EMPLEADO
WHERE SUELDO_EMP >= 200000 AND SUELDO_EMP<=800000
ORDER BY 2 DESC

----- CONSULTA 4 -----

SELECT 
      NUMRUT_EMP||'-'||DVRUT_EMP AS "RUT EMPLEADO",
      NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
      SUELDO_EMP AS "SUELDO ACTUAL",
      SUELDO_EMP*0.20 AS"BONIFICACION EXTRA"
FROM 
    EMPLEADO
WHERE SUELDO_EMP < 500000
ORDER BY APPATERNO_EMP ASC

----- CONSULTA 5 -----

---INFORME 1---

SELECT
    NRO_PROPIEDAD AS "NUMERO DE PROPIEDAD",
    FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE AS "SUPERFICIE",
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITARIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARIIENDO"
FROM 
    PROPIEDAD
WHERE FECHA_ENTREGA_PROPIEDAD BETWEEN '01/01/25' AND '31/12/25'

---INFORME 2---

SELECT
    NRO_PROPIEDAD AS "NUMERO DE PROPIEDAD",
    FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION PROPIEDAD",
    SUPERFICIE AS "SUPERFICIE",
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITARIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARIIENDO"
FROM 
    PROPIEDAD
WHERE FECHA_ENTREGA_PROPIEDAD >='01/02/10' AND FECHA_ENTREGA_PROPIEDAD < '01/03/10'
ORDER BY FECHA_ENTREGA_PROPIEDAD ASC

