CREATE TABLE TIPO_PROPIEDAD(
    ID_TIPO_PROPIEDAD VARCHAR2(1) NOT NULL PRIMARY KEY,
    DESC_TIPO_PROPIEDAD VARCHAR2(30)NOT NULL
);
CREATE TABLE COMUNA(
    ID_COMUNA NUMBER(3),
    NOMBRE_COMUNA VARCHAR2(30)
);

CREATE TABLE ESTADO_CIVIL(
    ID_ESTCIVIL NUMBER(1)NOT NULL PRIMARY KEY,
    DESC_ESTCIVIL VARCHAR2(25)NOT NULL
);

CREATE TABLE PROPIETARIO(
    NUMRUT_PROP NUMBER (10)NOT NULL PRIMARY KEY,
    DVRUT_PROP VARCHAR2 (1)NOT NULL,
    APPATERNO_PROP VARCHAR2(30)NOT NULL,
    APMATERNO_PROP VARCHAR2(30)NOT NULL,
    NOMBRE_PROP VARCHAR2(30)NOT NULL,
    DIRECCION_PROP VARCHAR2(60)NOT NULL,
    FONOFIJO_PROP VARCHAR2(15)NOT NULL,
    CELULAR_PROP VARCHAR2(15),
    ID_ESTCIVIL NUMBER(1)NOT NULL,
    ID_COMUNA NUMBER (3),
    CONSTRAINT FK_PROPIETARIO_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),
    CONSTRAINT FK_PROPIETARIO_ESTADO_CIVIL FOREIGN KEY (ID_ESTCIVIL) REFERENCES ESTADO_CIVIL(ID_ESTCIVIL)
);

CREATE TABLE EMPLEADO(
    NUMRUT_EMP NUMBER(10)NOT NULL PRIMARY KEY,
    DVRUT_EMP VARCHAR2(1)NOT NULL,
    APPATERNO_EMP VARCHAR2(30)NOT NULL,
    APMATERNO_EMP VARCHAR2(30)NOT NULL,
    NOMBRE_EMP VARCHAR2(30)NOT NULL,
    DIRECCION_EMP VARCHAR2(60)NOT NULL,
    FONOFIJO_EMO VARCHAR2(15)NOT NULL,
    CELULAR_EMP VARCHAR2(15),
    FECHA_NACI_EMP DATE,
    FECHA_ING_EMP DATE NOT NULL,
    SUELDO_EMP NUMBER(7)NOT NULL,
    ID_CATEGORIA_EMP NUMBER(1),
    ID_COMUNA NUMBER(3),
    ID_ESTCIVIL NUMBER(1)NOT NULL,
    CONSTRAINT FK_EMPLEADO_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),
    CONSTRAINT FK_EMPLEADO_ESTADO_CIVIL FOREIGN KEY (ID_ESTCIVIL) REFERENCES ESTADO_CIVIL(ID_ESTCIVIL)
);

CREATE TABLE CLIENTE(
    NUMRUT_CLI NUMBER(8)NOT NULL PRIMARY KEY,
    DV_RUT_CLI VARCHAR2(1)NOT NULL,
    APPATERNO_CLI VARCHAR2(30)NOT NULL,
    APMATERNO_CLI VARCHAR2(30)NOT NULL,
    NOMBRE_CLI VARCHAR2(30)NOT NULL,
    DIRECCION_CLI VARCHAR2(60)NOT NULL,
    FONOFIJO_CLI VARCHAR2(15)NOT NULL,
    CELULAR_CLI VARCHAR2(15),
    RENTA_CLI NUMBER(7)NOT NULL,
    ID_ESTCIVIL NUMBER(1)NOT NULL,
    CONSTRAINT FK_CLIENTE_ESTADO_CIVIL FOREIGN KEY (ID_ESTCIVIL) REFERENCES ESTADO_CIVIL(ID_ESTCIVIL)
);

CREATE TABLE PROPIEDAD(
    NRO_PROPIEDAD NUMBER(6)NOT NULL PRIMARY KEY,
    DIRECCION_PROPIEDAD VARCHAR2(60)NOT NULL,
    SUPERFICIE NUMBER(8,2)NOT NULL,
    VALOR_ARRIENDO NUMBER(7)NOT NULL,
    VALOR_CASTO_COMUN NUMBER(6)NOT NULL,
    NRO_DORMITORIOS NUMBER(2),
    NRO_BAÑOS NUMBER(1),
    NUMRUT_EMP NUMBER(10),
    NUMRUT_PROP NUMBER(10)NOT NULL,
    ID_TIPO_PROPIEDAD VARCHAR2(1)NOT NULL,
    ID_COMUNA NUMBER(3)NOT NULL,
    CONSTRAINT FK_PROPIEDAD_EMPLEADO FOREIGN KEY  (NUMRUT_EMP) REFERENCES EMPLEADO( NUMRUT_EMP),
    CONSTRAINT FK_PROPIEDAD_PROPIETARIO FOREIGN KEY (NUMRUT_PROP) REFERENCES PROPIETARIO(NUMRUT_PROP),
    CONSTRAINT FK_PROPIEDAD_TIPO_PROPIEDAD FOREIGN KEY (ID_TIPO_PROPIEDAD) REFERENCES TIPO_PROPIEDAD(ID_TIPO_PROPIEDAD),
    CONSTRAINT FK_PROPIEDAD_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),   
);

CREATE TABLE PROPIEDAD_ARRENDADA(
    NRO_PROPIEDAD NUMBER(6)NOT NULL,
    FECHA_INI_ARRIENDO DATE NOT NULL,
    PRIMARY KEY (NRO_PROPIEDAD,FECHA_INI_ARRIENDO)
    FECHA_TER_ARRIENDO DATE NOT NULL,
    NUMRUT_CLI NUMBER(10)NOT NULL,
    CONSTRAINT FK_PROPIEDAD_ARRENDADA_CLIENTE FOREIGN KEY (NUMRUT_CLI) REFERENCES CLIENTE(NUMRUT_CLI),
    CONSTRAINT FK_PROPIEDAD_ARRENDADA_PROPIEDAD FOREIGN KEY  (NRO_PROPIEDAD) REFERENCES PROPIEDAD( NRO_PROPIEDAD)
);
