----- CASO 1 -----
SELECT
     'EL EMPLEADO '||NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP||' NACIO EL '||FECNAC_EMP AS "LISTA DE COMPLEAÑOS"
FROM
    EMPLEADO
ORDER BY FECNAC_EMP,APPATERNO_EMP ASC;


----- CASO 2 -----
SELECT
    NUMRUT_CLI AS "RUN",
    DVRUT_CLI AS "DV",
    NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI AS "NOMBRE CLIENTE",
    RENTA_CLI AS "RENTA",
    FONOFIJO_CLI AS "FONO FIJO",
    CELULAR_CLI AS "CELULAR CLIENTE"
FROM
    CLIENTE
ORDER BY APPATERNO_CLI,APMATERNO_CLI ASC;


----- CASO 3 -----
SELECT
     NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEDO",
     SUELDO_EMP AS "SULDO",
     SUELDO_EMP *1.50 AS "BONO POR CAPACITACION"
FROM
    EMPLEADO
    
ORDER BY 3 DESC;


----- CASE 4 -----
SELECT
     NUMRUT_PRO AS "RUT"
FROM
    PROPIETARIO